// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PauseResumeResponse = { success: boolean, 
/**
 * Reason for failure (if success is false)
 */
reason: string | null, };
