// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewVoiceOptions = { 
/**
 * Voice ID to preview
 */
voiceId: string, 
/**
 * Optional custom sample text (uses default if not provided)
 */
text: string | null, };
