// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueMode } from "./QueueMode";

export type SpeakOptions = { 
/**
 * The text to speak (max 10,000 characters)
 */
text: string, 
/**
 * The language/locale code (e.g., "en-US", "pt-BR", "ja-JP")
 */
language: string | null, 
/**
 * Specific voice ID to use (from getVoices). Takes priority over language
 */
voiceId: string | null, 
/**
 * Speech rate (0.1 to 4.0, where 1.0 = normal)
 */
rate: number | null, 
/**
 * Pitch (0.5 to 2.0, where 1.0 = normal)
 */
pitch: number | null, 
/**
 * Volume (0.0 to 1.0, where 1.0 = full volume)
 */
volume: number | null, 
/**
 * Queue mode: "flush" (default) or "add"
 */
queueMode: QueueMode | null, };
