// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Voice = { 
/**
 * Unique identifier for the voice
 */
id: string, 
/**
 * Display name of the voice
 */
name: string, 
/**
 * Language code (e.g., "en-US")
 */
language: string, };
